name: Build AIX Extension

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Clone App Inventor Sources
        run: git clone https://github.com/mit-cml/appinventor-sources.git

      - name: Build App Inventor Components
        run: |
          cd appinventor-sources/appinventor
          ant MakeExtensions

      - name: Compile Extension
        run: |
          mkdir build
          javac -cp appinventor-sources/appinventor/buildserver/build/classes -d build src/dev/Dev.java

      - name: Package AIX
        run: |
          cd build
          zip -r Dev.aix *

      - name: Upload Extension
        uses: actions/upload-artifact@v4
        with:
          name: Dev-extension
          path: build/Dev.aix
