name: Build Extension
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build AIX
        uses: pavi2410/AIX-Action@main
        with:
          name: abajaba

      - name: Upload AIX
        uses: actions/upload-artifact@v3
        with:
          name: abajaba_extension
          path: out/*.aix
