name: Build MIT App Inventor Extension

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk

      - name: Download App Inventor Runtime
        run: |
          git clone https://github.com/mit-cml/appinventor-sources.git

      - name: Compile Extension
        run: |
          mkdir build
          javac -cp "/usr/lib/android-sdk/platforms/android-30/android.jar:appinventor-sources/appinventor/components/build/classes" \
          -d build src/dev/Dev.java

      - name: Package AIX
        run: |
          cd build
          zip -r Dev.aix *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dev-extension
          path: build/Dev.aix
